import json
from .jsonDataObject import jsonDataObject

class UserExtended(jsonDataObject):
    table = "userExtended"  # Hardcoded table name
    key_columns = "id, ruleset_id"
    json_columns = {
        "playstyle",
        "profile_order",
        "badges",
        "current_season_stats",
        "monthly_playcounts",
        "previous_usernames",
        "replays_watched_counts",
        "user_achievements",
        "rank_history",
        "account_history",
        "active_tournament_banners",
        "groups",
        "matchmaking_stats",
        "page",
        "statistics_variants",
        "active_tournament_banner",
    }
    flatten_columns = {
        "country",
        "cover",
        "kudosu",
        "team",
        "daily_challenge_user_stats",
        "rank_highest",
        "statistics_level",
        "statistics_grade_counts",
        "statistics_rank",
    }

    column_list = {
        "id",
        "playmode",
        "account_history",
        "active_tournament_banner",
        "active_tournament_banners",
        "avatar_url",
        "badges",
        "beatmap_playcounts_count",
        "comments_count",
        "current_season_stats",
        "country_code",
        "country_name",
        "cover_custom_url",
        "cover_id",
        "cover_url",
        "daily_challenge_user_stats_daily_streak_best",
        "daily_challenge_user_stats_daily_streak_current",
        "daily_challenge_user_stats_last_update",
        "daily_challenge_user_stats_last_weekly_streak",
        "daily_challenge_user_stats_playcount",
        "daily_challenge_user_stats_top_10p_placements",
        "daily_challenge_user_stats_top_50p_placements",
        "daily_challenge_user_stats_user_id",
        "daily_challenge_user_stats_weekly_streak_best",
        "daily_challenge_user_stats_weekly_streak_current",
        "default_group",
        "discord",
        "favourite_beatmapset_count",
        "follower_count",
        "graveyard_beatmapset_count",
        "groups",
        "guest_beatmapset_count",
        "has_supported",
        "interests",
        "is_active",
        "is_bot",
        "is_deleted",
        "is_online",
        "is_supporter",
        "join_date",
        "kudosu_available",
        "kudosu_total",
        "last_visit",
        "location",
        "loved_beatmapset_count",
        "mapping_follower_count",
        "max_blocks",
        "max_friends",
        "monthly_playcounts",
        "nominated_beatmapset_count",
        "occupation",
        "pending_beatmapset_count",
        "playstyle",
        "pm_friends_only",
        "post_count",
        "previous_usernames",
        "profile_colour",
        "profile_hue",
        "profile_order",
        "rank_highest_rank",
        "rank_highest_updated_at",
        "rank_history",
        "ranked_and_approved_beatmapset_count",
        "ranked_beatmapset_count",
        "replays_watched_counts",
        "scores_best_count",
        "scores_first_count",
        "scores_pinned_count",
        "scores_recent_count",
        "statistics_count_100",
        "statistics_count_300",
        "statistics_count_50",
        "statistics_count_miss",
        "statistics_country_rank",
        "statistics_global_rank",
        "statistics_global_rank_exp",
        "statistics_grade_counts_ss",
        "statistics_grade_counts_ssh",
        "statistics_grade_counts_s",
        "statistics_grade_counts_sh",
        "statistics_grade_counts_a",
        "statistics_hit_accuracy",
        "statistics_is_ranked",
        "statistics_level_current",
        "statistics_level_progress",
        "statistics_maximum_combo",
        "statistics_play_count",
        "statistics_play_time",
        "statistics_pp",
        "statistics_pp_exp",
        "statistics_rank_country",
        "statistics_ranked_score",
        "statistics_replays_watched_by_others",
        "statistics_total_hits",
        "statistics_total_score",
        "support_level",
        "team_flag_url",
        "team_id",
        "team_name",
        "team_short_name",
        "title",
        "title_url",
        "twitter",
        "unranked_beatmapset_count",
        "user_achievements",
        "username",
        "website",
        "matchmaking_stats",
        "statistics_global_rank_percent",
        "page"
    }

    def __init__(self, user, mode):
        #duplicate
        user.pop("rankHistory")
        user["ruleset_id"] = {"osu": 0, "taiko": 1, "fruits": 2, "mania": 3}[mode]
        for key, value in user.pop("statistics", {}).items():
            user[f"statistics_{key}"] = value

        super().__init__(
            user,
            self.table,
            self.key_columns,
            self.flatten_columns,
            self.json_columns,
            self.column_list,
        )
