CREATE OR REPLACE VIEW public.beatmapFull AS
SELECT
    -- Canonical query surface: all the stuff you already denormalised
    bl.beatmap_id,
    bl.mapper_id,
    bl.beatmapset_id,
    bl."mode",
    bl.status,
    bl.stars,
    bl.od,
    bl.ar,
    bl.bpm,
    bl.cs,
    bl.hp,
    bl.length,
    bl.drain_time,
    bl.count_circles,
    bl.count_sliders,
    bl.count_spinners,
    bl.max_combo,
    bl.pass_count,
    bl.play_count,
    bl.fc_count,
    bl.ss_count,
    bl.favourite_count,
    bl.ranked_date,
    bl.submitted_date,
    bl.last_updated,
    bl."version",
    bl.title,
    bl.artist,
    bl."source",
    bl.tags,
    bl.checksum,
    bl.track_id,
    bl.pack,
    bl.lchg_time,
    bl.mapper,
    bl.is_nsfw,
    bl.beatmap_offset,
    bl.rating,
    bl.is_spotlight,
    bl.genre,
    bl."language",
    bl.has_video,
    bl.has_storyboard,
    bl.download_disabled,
    b.mode            AS mode_str,
    b.convert         AS is_convert,
    b.current_user_playcount,
    b.deleted_at      AS beatmap_deleted_at,
    b.is_scoreable    AS beatmap_is_scoreable,
    b.ranked          AS ranked_raw,
    b.url,
    b.beatmapset_artist_unicode,
    b.beatmapset_hype_current,
    b.beatmapset_hype_required,
    b.beatmapset_play_count,
    b.beatmapset_preview_url,
    b.beatmapset_status         AS beatmapset_status_raw,
    b.beatmapset_title_unicode,
    b.beatmapset_user_id,
    b.beatmapset_bpm,
    b.beatmapset_can_be_hyped,
    b.beatmapset_deleted_at,
    b.beatmapset_discussion_enabled,
    b.beatmapset_discussion_locked,
    b.beatmapset_is_scoreable,
    b.beatmapset_last_updated   AS beatmapset_last_updated_raw,
    b.beatmapset_legacy_thread_url,
    b.beatmapset_ranked,
    b.beatmapset_storyboard     AS beatmapset_storyboard_raw,
    b.beatmapset_tags           AS beatmapset_tags_raw,
    b.failtimes,
    b.beatmapset_availability,
    b.owners,
    b.beatmapset_nominations_summary,
    b.beatmapset_covers,
    b.beatmapset_ratings

FROM public.beatmaplive bl
JOIN public.beatmap b
  ON b.id = bl.beatmap_id;
