CREATE TABLE IF NOT EXISTS public.scorelive (
	id int8 NOT NULL,
	beatmap_id_fk int4 NOT NULL,
	user_id_fk int4 NOT NULL,
	accuracy numeric NOT NULL,
	best_id int4 NULL,
	build_id int4 NULL,
	classic_total_score int8 NOT NULL,
	ended_at timestamptz NOT NULL,
	has_replay bool NOT NULL,
	is_perfect_combo bool NOT NULL,
	legacy_perfect bool NOT NULL,
	legacy_score_id int8 NULL,
	legacy_total_score int8 NOT NULL,
	max_combo int4 NOT NULL,
	maximum_statistics_perfect int4 NULL,
	maximum_statistics_great int4 NULL,
	maximum_statistics_miss int4 NULL,
	maximum_statistics_ignore_hit int4 NULL,
	maximum_statistics_ignore_miss int4 NULL,
	maximum_statistics_slider_tail_hit int4 NULL,
	maximum_statistics_legacy_combo_increase int4 NULL,
	maximum_statistics_large_bonus int4 NULL,
	maximum_statistics_large_tick_hit int4 NULL,
	maximum_statistics_small_bonus int4 NULL,
	maximum_statistics_small_tick_hit int4 NULL,
	mods jsonb NOT NULL,
	passed bool NOT NULL,
	pp numeric NULL,
	"preserve" bool NOT NULL,
	processed bool NOT NULL,
	grade varchar(3) NOT NULL,
	ranked bool NOT NULL,
	replay bool NOT NULL,
	ruleset_id int4 NOT NULL,
	started_at timestamptz NULL,
	statistics_perfect int4 NULL,
	statistics_great int4 NULL,
	statistics_good int4 NULL,
	statistics_ok int4 NULL,
	statistics_meh int4 NULL,
	statistics_miss int4 NULL,
	statistics_ignore_hit int4 NULL,
	statistics_ignore_miss int4 NULL,
	statistics_slider_tail_hit int4 NULL,
	statistics_slider_tail_miss int4 NULL,
	statistics_large_bonus int4 NULL,
	statistics_large_tick_hit int4 NULL,
	statistics_large_tick_miss int4 NULL,
	statistics_small_bonus int4 NULL,
	statistics_small_tick_hit int4 NULL,
	statistics_small_tick_miss int4 NULL,
	statistics_combo_break int4 NULL,
	total_score int8 NULL,
	total_score_without_mods int8 NULL,
	"type" varchar(50) NOT NULL,
	highest_score bool DEFAULT false NULL,
	highest_pp bool DEFAULT false NULL,
	"rank" int4 NULL,
	mod_acronyms _text NULL,
	mod_speed_change numeric NULL,
	difficulty_reducing bool DEFAULT false NULL,
	difficulty_removing bool DEFAULT false NULL,
	CONSTRAINT scorelive_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_scorelive_ended_at ON public.scorelive USING brin (ended_at);
CREATE INDEX IF NOT EXISTS idx_scorelive_highest_only ON public.scorelive USING btree (beatmap_id_fk, user_id_fk) WHERE (highest_score = true);
CREATE INDEX IF NOT EXISTS idx_scorelive_mods_path ON public.scorelive USING gin (mods jsonb_path_ops);
CREATE INDEX IF NOT EXISTS scorelive_beatmap ON public.scorelive USING btree (beatmap_id_fk);
CREATE INDEX IF NOT EXISTS scorelive_user ON public.scorelive USING btree (user_id_fk);
CREATE INDEX IF NOT EXISTS scorelive_score_ruleset ON public.scorelive (beatmap_id_fk, user_id_fk, ruleset_id, classic_total_score DESC);
CREATE INDEX IF NOT EXISTS scorelive_pp_ruleset ON public.scorelive (beatmap_id_fk, user_id_fk, ruleset_id, pp DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_scorelive_highest_by_user ON public.scorelive (user_id_fk) WHERE highest_score = true;