CREATE TABLE IF NOT EXISTS userFruits (
    id BIGINT PRIMARY KEY,
    avatar_url TEXT,
    cover_custom_url TEXT,
    cover_id BIGINT,
    cover_url TEXT,
    country_code VARCHAR(2),
    country_name TEXT,
    default_group TEXT,
    groups JSONB,
    is_active BOOLEAN,
    is_bot BOOLEAN,
    is_deleted BOOLEAN,
    is_online BOOLEAN,
    is_supporter BOOLEAN,
    last_visit TIMESTAMPTZ,
    fruits_count_100 INTEGER,
    fruits_count_300 INTEGER,
    fruits_count_50 INTEGER,
    fruits_count_miss INTEGER,
    fruits_global_rank INTEGER,
    fruits_global_rank_exp INTEGER,
    fruits_grade_counts_a INTEGER,
    fruits_grade_counts_s INTEGER,
    fruits_grade_counts_sh INTEGER,
    fruits_grade_counts_ss INTEGER,
    fruits_grade_counts_ssh INTEGER,
    fruits_hit_accuracy DOUBLE PRECISION,
    fruits_is_ranked BOOLEAN,
    fruits_level_current INTEGER,
    fruits_level_progress INTEGER,
    fruits_maximum_combo INTEGER,
    fruits_play_count INTEGER,
    fruits_play_time INTEGER,
    fruits_pp DOUBLE PRECISION,
    fruits_pp_exp DOUBLE PRECISION,
    fruits_ranked_score BIGINT,
    fruits_replays_watched_by_others INTEGER,
    fruits_total_hits BIGINT,
    fruits_total_score BIGINT,
    pm_friends_only BOOLEAN,
    profile_colour TEXT,
    team_flag_url TEXT,
    team_id INTEGER,
    team_name TEXT,
    team_short_name TEXT,
    username TEXT NOT NULL
);
