CREATE TABLE IF NOT EXISTS userMania (
    id BIGINT PRIMARY KEY,
    avatar_url TEXT,
    cover_custom_url TEXT,
    cover_id BIGINT,
    cover_url TEXT,
    country_code VARCHAR(2),
    country_name TEXT,
    default_group TEXT,
    groups JSONB,
    is_active BOOLEAN,
    is_bot BOOLEAN,
    is_deleted BOOLEAN,
    is_online BOOLEAN,
    is_supporter BOOLEAN,
    last_visit TIMESTAMPTZ,
    mania_count_100 INTEGER,
    mania_count_300 INTEGER,
    mania_count_50 INTEGER,
    mania_count_miss INTEGER,
    mania_global_rank INTEGER,
    mania_global_rank_exp INTEGER,
    mania_grade_counts_a INTEGER,
    mania_grade_counts_s INTEGER,
    mania_grade_counts_sh INTEGER,
    mania_grade_counts_ss INTEGER,
    mania_grade_counts_ssh INTEGER,
    mania_hit_accuracy DOUBLE PRECISION,
    mania_is_ranked BOOLEAN,
    mania_level_current INTEGER,
    mania_level_progress INTEGER,
    mania_maximum_combo INTEGER,
    mania_play_count INTEGER,
    mania_play_time INTEGER,
    mania_pp DOUBLE PRECISION,
    mania_pp_exp DOUBLE PRECISION,
    mania_ranked_score BIGINT,
    mania_replays_watched_by_others INTEGER,
    mania_total_hits BIGINT,
    mania_total_score BIGINT,
    pm_friends_only BOOLEAN,
    profile_colour TEXT,
    team_flag_url TEXT,
    team_id INTEGER,
    team_name TEXT,
    team_short_name TEXT,
    username TEXT NOT NULL,
    registered BOOLEAN DEFAULT FALSE
);
