CREATE TABLE IF  NOT EXISTS public.userlive (
	user_id int8 NOT NULL,
	username text NOT NULL,
	country_code varchar(2) NULL,
	country_name text NULL,
	osu_count_100 int4 NULL,
	osu_count_300 int4 NULL,
	osu_count_50 int4 NULL,
	osu_count_miss int4 NULL,
	osu_global_rank int4 NULL,
	osu_grade_counts_a int4 NULL,
	osu_grade_counts_s int4 NULL,
	osu_grade_counts_sh int4 NULL,
	osu_grade_counts_ss int4 NULL,
	osu_grade_counts_ssh int4 NULL,
	osu_hit_accuracy float8 NULL,
	osu_level_current int4 NULL,
	osu_level_progress int4 NULL,
	osu_maximum_combo int4 NULL,
	osu_play_count int4 NULL,
	osu_play_time int4 NULL,
	osu_pp float8 NULL,
	osu_ranked_score int8 NULL,
	osu_replays_watched_by_others int4 NULL,
	osu_total_hits int8 NULL,
	osu_total_score int8 NULL,
	taiko_count_100 int4 NULL,
	taiko_count_300 int4 NULL,
	taiko_count_50 int4 NULL,
	taiko_count_miss int4 NULL,
	taiko_global_rank int4 NULL,
	taiko_grade_counts_a int4 NULL,
	taiko_grade_counts_s int4 NULL,
	taiko_grade_counts_sh int4 NULL,
	taiko_grade_counts_ss int4 NULL,
	taiko_grade_counts_ssh int4 NULL,
	taiko_hit_accuracy float8 NULL,
	taiko_level_current int4 NULL,
	taiko_level_progress int4 NULL,
	taiko_maximum_combo int4 NULL,
	taiko_play_count int4 NULL,
	taiko_play_time int4 NULL,
	taiko_pp float8 NULL,
	taiko_ranked_score int8 NULL,
	taiko_replays_watched_by_others int4 NULL,
	taiko_total_hits int8 NULL,
	taiko_total_score int8 NULL,
	fruits_count_100 int4 NULL,
	fruits_count_300 int4 NULL,
	fruits_count_50 int4 NULL,
	fruits_count_miss int4 NULL,
	fruits_global_rank int4 NULL,
	fruits_grade_counts_a int4 NULL,
	fruits_grade_counts_s int4 NULL,
	fruits_grade_counts_sh int4 NULL,
	fruits_grade_counts_ss int4 NULL,
	fruits_grade_counts_ssh int4 NULL,
	fruits_hit_accuracy float8 NULL,
	fruits_level_current int4 NULL,
	fruits_level_progress int4 NULL,
	fruits_maximum_combo int4 NULL,
	fruits_play_count int4 NULL,
	fruits_play_time int4 NULL,
	fruits_pp float8 NULL,
	fruits_ranked_score int8 NULL,
	fruits_replays_watched_by_others int4 NULL,
	fruits_total_hits int8 NULL,
	fruits_total_score int8 NULL,
	mania_count_100 int4 NULL,
	mania_count_300 int4 NULL,
	mania_count_50 int4 NULL,
	mania_count_miss int4 NULL,
	mania_global_rank int4 NULL,
	mania_grade_counts_a int4 NULL,
	mania_grade_counts_s int4 NULL,
	mania_grade_counts_sh int4 NULL,
	mania_grade_counts_ss int4 NULL,
	mania_grade_counts_ssh int4 NULL,
	mania_hit_accuracy float8 NULL,
	mania_level_current int4 NULL,
	mania_level_progress int4 NULL,
	mania_maximum_combo int4 NULL,
	mania_play_count int4 NULL,
	mania_play_time int4 NULL,
	mania_pp float8 NULL,
	mania_ranked_score int8 NULL,
	mania_replays_watched_by_others int4 NULL,
	mania_total_hits int8 NULL,
	mania_total_score int8 NULL,
	team_flag_url text NULL,
	team_id int4 NULL,
	team_name text NULL,
	team_short_name text NULL,
	total_ranked_score int8 GENERATED ALWAYS AS (osu_ranked_score + taiko_ranked_score + fruits_ranked_score + mania_ranked_score) STORED NULL,
	total_grade_counts_a int8 GENERATED ALWAYS AS ((osu_grade_counts_a + taiko_grade_counts_a + fruits_grade_counts_a + mania_grade_counts_a)) STORED NULL,
	total_grade_counts_s int8 GENERATED ALWAYS AS ((osu_grade_counts_s + taiko_grade_counts_s + fruits_grade_counts_s + mania_grade_counts_s)) STORED NULL,
	total_grade_counts_sh int8 GENERATED ALWAYS AS ((osu_grade_counts_sh + taiko_grade_counts_sh + fruits_grade_counts_sh + mania_grade_counts_sh)) STORED NULL,
	total_grade_counts_ss int8 GENERATED ALWAYS AS ((osu_grade_counts_ss + taiko_grade_counts_ss + fruits_grade_counts_ss + mania_grade_counts_ss)) STORED NULL,
	total_grade_counts_ssh int8 GENERATED ALWAYS AS ((osu_grade_counts_ssh + taiko_grade_counts_ssh + fruits_grade_counts_ssh + mania_grade_counts_sh)) STORED NULL,
	total_play_count int8 GENERATED ALWAYS AS ((osu_play_count + taiko_play_count + fruits_play_count + mania_play_count)) STORED NULL,
	total_play_time int8 GENERATED ALWAYS AS ((osu_play_time + taiko_play_time + fruits_play_time + mania_play_time)) STORED NULL,
	total_pp int8 GENERATED ALWAYS AS ((osu_pp + taiko_pp + fruits_pp + mania_pp)) STORED NULL,
	total_replays_watched_by_others int8 GENERATED ALWAYS AS ((osu_replays_watched_by_others + taiko_replays_watched_by_others + fruits_replays_watched_by_others + mania_replays_watched_by_others)) STORED NULL,
	CONSTRAINT userlive_pkey PRIMARY KEY (user_id)
);