CREATE TABLE IF NOT EXISTS userHistory (
    "id" BIGINT,
    "record_date" DATE,
    "username" TEXT NOT NULL,
    "post_count" INTEGER,
    "beatmap_playcounts_count" INTEGER,
    "comments_count" INTEGER,
    "favourite_beatmapset_count" INTEGER,
    "follower_count" INTEGER,
    "graveyard_beatmapset_count" INTEGER,
    "guest_beatmapset_count" INTEGER,
    "loved_beatmapset_count" INTEGER,
    "mapping_follower_count" INTEGER,
    "nominated_beatmapset_count" INTEGER,
    "pending_beatmapset_count" INTEGER,
    "ranked_beatmapset_count" INTEGER,
    "scores_best_count" INTEGER,
    "scores_first_count" INTEGER,
    "scores_pinned_count" INTEGER,
    "scores_recent_count" INTEGER,
    "ranked_and_approved_beatmapset_count" INTEGER,
    "unranked_beatmapset_count" INTEGER,
    "statistics_count_100" INTEGER,
    "statistics_count_300" INTEGER,
    "statistics_count_50" INTEGER,
    "statistics_count_miss" INTEGER,
    "statistics_global_rank" INTEGER,
    "statistics_global_rank_exp" INTEGER,
    "statistics_pp" DECIMAL,
    "statistics_pp_exp" DECIMAL,
    "statistics_ranked_score" BIGINT,
    "statistics_hit_accuracy" DECIMAL,
    "statistics_play_count" INTEGER,
    "statistics_play_time" INTEGER,
    "statistics_total_score" BIGINT,
    "statistics_total_hits" BIGINT,
    "statistics_maximum_combo" INTEGER,
    "statistics_replays_watched_by_others" INTEGER,
    "statistics_is_ranked" BOOLEAN,
    "statistics_country_rank" INTEGER,
    "statistics_grade_counts_ss" INTEGER,
    "statistics_grade_counts_ssh" INTEGER,
    "statistics_grade_counts_s" INTEGER,
    "statistics_grade_counts_sh" INTEGER,
    "statistics_grade_counts_a" INTEGER,
    "kudosu_available" INTEGER,
    "kudosu_total" INTEGER,
    "rank_highest_rank" INTEGER,
    "rank_highest_updated_at" TIMESTAMP WITH TIME ZONE,
    "daily_challenge_user_stats_daily_streak_best" INTEGER,
    "daily_challenge_user_stats_daily_streak_current" INTEGER,
    "daily_challenge_user_stats_last_update" TIMESTAMP WITH TIME ZONE,
    "daily_challenge_user_stats_last_weekly_streak" INTEGER,
    "daily_challenge_user_stats_playcount" INTEGER,
    "daily_challenge_user_stats_top_10p_placements" INTEGER,
    "daily_challenge_user_stats_top_50p_placements" INTEGER,
    "daily_challenge_user_stats_user_id" BIGINT,
    "daily_challenge_user_stats_weekly_streak_best" INTEGER,
    "daily_challenge_user_stats_weekly_streak_current" INTEGER,
    PRIMARY KEY (id, record_date)
);
