CREATE TABLE IF NOT EXISTS userLive (
    user_id BIGINT PRIMARY KEY,
    username TEXT NOT NULL,
    country_code VARCHAR(2),
    country_name TEXT,
    osu_count_100 INTEGER,
    osu_count_300 INTEGER,  
    osu_count_50 INTEGER,
    osu_count_miss INTEGER,
    osu_global_rank INTEGER,
    osu_grade_counts_a INTEGER,
    osu_grade_counts_s INTEGER,
    osu_grade_counts_sh INTEGER,
    osu_grade_counts_ss INTEGER,
    osu_grade_counts_ssh INTEGER,
    osu_hit_accuracy DOUBLE PRECISION,
    osu_level_current INTEGER,
    osu_level_progress INTEGER,
    osu_maximum_combo INTEGER,
    osu_play_count INTEGER,
    osu_play_time INTEGER,
    osu_pp DOUBLE PRECISION,
    osu_ranked_score BIGINT,
    osu_replays_watched_by_others INTEGER,
    osu_total_hits BIGINT,
    osu_total_score BIGINT,
    taiko_count_100 INTEGER,
    taiko_count_300 INTEGER,
    taiko_count_50 INTEGER,
    taiko_count_miss INTEGER,
    taiko_global_rank INTEGER,
    taiko_grade_counts_a INTEGER,
    taiko_grade_counts_s INTEGER,
    taiko_grade_counts_sh INTEGER,
    taiko_grade_counts_ss INTEGER,
    taiko_grade_counts_ssh INTEGER,
    taiko_hit_accuracy DOUBLE PRECISION,
    taiko_level_current INTEGER,
    taiko_level_progress INTEGER,
    taiko_maximum_combo INTEGER,
    taiko_play_count INTEGER,
    taiko_play_time INTEGER,
    taiko_pp DOUBLE PRECISION,
    taiko_ranked_score BIGINT,
    taiko_replays_watched_by_others INTEGER,
    taiko_total_hits BIGINT,
    taiko_total_score BIGINT,
    fruits_count_100 INTEGER,
    fruits_count_300 INTEGER,
    fruits_count_50 INTEGER,
    fruits_count_miss INTEGER,
    fruits_global_rank INTEGER,
    fruits_grade_counts_a INTEGER,
    fruits_grade_counts_s INTEGER,
    fruits_grade_counts_sh INTEGER,
    fruits_grade_counts_ss INTEGER,
    fruits_grade_counts_ssh INTEGER,
    fruits_hit_accuracy DOUBLE PRECISION,
    fruits_level_current INTEGER,
    fruits_level_progress INTEGER,
    fruits_maximum_combo INTEGER,
    fruits_play_count INTEGER,
    fruits_play_time INTEGER,
    fruits_pp DOUBLE PRECISION,
    fruits_ranked_score BIGINT,
    fruits_replays_watched_by_others INTEGER,
    fruits_total_hits BIGINT,
    fruits_total_score BIGINT,
    mania_count_100 INTEGER,
    mania_count_300 INTEGER,
    mania_count_50 INTEGER,
    mania_count_miss INTEGER,
    mania_global_rank INTEGER,
    mania_grade_counts_a INTEGER,
    mania_grade_counts_s INTEGER,
    mania_grade_counts_sh INTEGER,
    mania_grade_counts_ss INTEGER,
    mania_grade_counts_ssh INTEGER,
    mania_hit_accuracy DOUBLE PRECISION,
    mania_level_current INTEGER,
    mania_level_progress INTEGER,
    mania_maximum_combo INTEGER,
    mania_play_count INTEGER,
    mania_play_time INTEGER,
    mania_pp DOUBLE PRECISION,
    mania_ranked_score BIGINT,
    mania_replays_watched_by_others INTEGER,
    mania_total_hits BIGINT,
    mania_total_score BIGINT,
    team_flag_url TEXT,
    team_id INTEGER,
    team_name TEXT,
    team_short_name TEXT
);
