INSERT INTO public.userlive (
    user_id,
    username,
    country_code,
    country_name,
    osu_count_100,
    osu_count_300,
    osu_count_50,
    osu_count_miss,
    osu_global_rank,
    osu_grade_counts_a,
    osu_grade_counts_s,
    osu_grade_counts_sh,
    osu_grade_counts_ss,
    osu_grade_counts_ssh,
    osu_hit_accuracy,
    osu_level_current,
    osu_level_progress,
    osu_maximum_combo,
    osu_play_count,
    osu_play_time,
    osu_pp,
    osu_ranked_score,
    osu_replays_watched_by_others,
    osu_total_hits,
    osu_total_score,
    taiko_count_100,
    taiko_count_300,
    taiko_count_50,
    taiko_count_miss,
    taiko_global_rank,
    taiko_grade_counts_a,
    taiko_grade_counts_s,
    taiko_grade_counts_sh,
    taiko_grade_counts_ss,
    taiko_grade_counts_ssh,
    taiko_hit_accuracy,
    taiko_level_current,
    taiko_level_progress,
    taiko_maximum_combo,
    taiko_play_count,
    taiko_play_time,
    taiko_pp,
    taiko_ranked_score,
    taiko_replays_watched_by_others,
    taiko_total_hits,
    taiko_total_score,
    fruits_count_100,
    fruits_count_300,
    fruits_count_50,
    fruits_count_miss,
    fruits_global_rank,
    fruits_grade_counts_a,
    fruits_grade_counts_s,
    fruits_grade_counts_sh,
    fruits_grade_counts_ss,
    fruits_grade_counts_ssh,
    fruits_hit_accuracy,
    fruits_level_current,
    fruits_level_progress,
    fruits_maximum_combo,
    fruits_play_count,
    fruits_play_time,
    fruits_pp,
    fruits_ranked_score,
    fruits_replays_watched_by_others,
    fruits_total_hits,
    fruits_total_score,
    mania_count_100,
    mania_count_300,
    mania_count_50,
    mania_count_miss,
    mania_global_rank,
    mania_grade_counts_a,
    mania_grade_counts_s,
    mania_grade_counts_sh,
    mania_grade_counts_ss,
    mania_grade_counts_ssh,
    mania_hit_accuracy,
    mania_level_current,
    mania_level_progress,
    mania_maximum_combo,
    mania_play_count,
    mania_play_time,
    mania_pp,
    mania_ranked_score,
    mania_replays_watched_by_others,
    mania_total_hits,
    mania_total_score,
    team_flag_url,
    team_id,
    team_name,
    team_short_name
)
SELECT
    um.id,
    um.username,
    um.country_code,
    um.country_name,
    um.osu_count_100,
    um.osu_count_300,
    um.osu_count_50,
    um.osu_count_miss,
    um.osu_global_rank,
    um.osu_grade_counts_a,
    um.osu_grade_counts_s,
    um.osu_grade_counts_sh,
    um.osu_grade_counts_ss,
    um.osu_grade_counts_ssh,
    um.osu_hit_accuracy,
    um.osu_level_current,
    um.osu_level_progress,
    um.osu_maximum_combo,
    um.osu_play_count,
    um.osu_play_time,
    um.osu_pp,
    um.osu_ranked_score,
    um.osu_replays_watched_by_others,
    um.osu_total_hits,
    um.osu_total_score,
    um.taiko_count_100,
    um.taiko_count_300,
    um.taiko_count_50,
    um.taiko_count_miss,
    um.taiko_global_rank,
    um.taiko_grade_counts_a,
    um.taiko_grade_counts_s,
    um.taiko_grade_counts_sh,
    um.taiko_grade_counts_ss,
    um.taiko_grade_counts_ssh,
    um.taiko_hit_accuracy,
    um.taiko_level_current,
    um.taiko_level_progress,
    um.taiko_maximum_combo,
    um.taiko_play_count,
    um.taiko_play_time,
    um.taiko_pp,
    um.taiko_ranked_score,
    um.taiko_replays_watched_by_others,
    um.taiko_total_hits,
    um.taiko_total_score,
    um.fruits_count_100,
    um.fruits_count_300,
    um.fruits_count_50,
    um.fruits_count_miss,
    um.fruits_global_rank,
    um.fruits_grade_counts_a,
    um.fruits_grade_counts_s,
    um.fruits_grade_counts_sh,
    um.fruits_grade_counts_ss,
    um.fruits_grade_counts_ssh,
    um.fruits_hit_accuracy,
    um.fruits_level_current,
    um.fruits_level_progress,
    um.fruits_maximum_combo,
    um.fruits_play_count,
    um.fruits_play_time,
    um.fruits_pp,
    um.fruits_ranked_score,
    um.fruits_replays_watched_by_others,
    um.fruits_total_hits,
    um.fruits_total_score,
    um.mania_count_100,
    um.mania_count_300,
    um.mania_count_50,
    um.mania_count_miss,
    um.mania_global_rank,
    um.mania_grade_counts_a,
    um.mania_grade_counts_s,
    um.mania_grade_counts_sh,
    um.mania_grade_counts_ss,
    um.mania_grade_counts_ssh,
    um.mania_hit_accuracy,
    um.mania_level_current,
    um.mania_level_progress,
    um.mania_maximum_combo,
    um.mania_play_count,
    um.mania_play_time,
    um.mania_pp,
    um.mania_ranked_score,
    um.mania_replays_watched_by_others,
    um.mania_total_hits,
    um.mania_total_score,
    um.team_flag_url,
    um.team_id,
    um.team_name,
    um.team_short_name
FROM userMaster um
    inner join userLive ul on um.id = ul.user_id
ON CONFLICT (user_id)
DO UPDATE SET
    username = EXCLUDED.username,
    country_code = EXCLUDED.country_code,
    country_name = EXCLUDED.country_name,
    osu_count_100 = EXCLUDED.osu_count_100,
    osu_count_300 = EXCLUDED.osu_count_300,
    osu_count_50 = EXCLUDED.osu_count_50,
    osu_count_miss = EXCLUDED.osu_count_miss,
    osu_global_rank = EXCLUDED.osu_global_rank,
    osu_grade_counts_a = EXCLUDED.osu_grade_counts_a,
    osu_grade_counts_s = EXCLUDED.osu_grade_counts_s,
    osu_grade_counts_sh = EXCLUDED.osu_grade_counts_sh,
    osu_grade_counts_ss = EXCLUDED.osu_grade_counts_ss,
    osu_grade_counts_ssh = EXCLUDED.osu_grade_counts_ssh,
    osu_hit_accuracy = EXCLUDED.osu_hit_accuracy,
    osu_level_current = EXCLUDED.osu_level_current,
    osu_level_progress = EXCLUDED.osu_level_progress,
    osu_maximum_combo = EXCLUDED.osu_maximum_combo,
    osu_play_count = EXCLUDED.osu_play_count,
    osu_play_time = EXCLUDED.osu_play_time,
    osu_pp = EXCLUDED.osu_pp,
    osu_ranked_score = EXCLUDED.osu_ranked_score,
    osu_replays_watched_by_others = EXCLUDED.osu_replays_watched_by_others,
    osu_total_hits = EXCLUDED.osu_total_hits,
    osu_total_score = EXCLUDED.osu_total_score,
    taiko_count_100 = EXCLUDED.taiko_count_100,
    taiko_count_300 = EXCLUDED.taiko_count_300,
    taiko_count_50 = EXCLUDED.taiko_count_50,
    taiko_count_miss = EXCLUDED.taiko_count_miss,
    taiko_global_rank = EXCLUDED.taiko_global_rank,
    taiko_grade_counts_a = EXCLUDED.taiko_grade_counts_a,
    taiko_grade_counts_s = EXCLUDED.taiko_grade_counts_s,
    taiko_grade_counts_sh = EXCLUDED.taiko_grade_counts_sh,
    taiko_grade_counts_ss = EXCLUDED.taiko_grade_counts_ss,
    taiko_grade_counts_ssh = EXCLUDED.taiko_grade_counts_ssh,
    taiko_hit_accuracy = EXCLUDED.taiko_hit_accuracy,
    taiko_level_current = EXCLUDED.taiko_level_current,
    taiko_level_progress = EXCLUDED.taiko_level_progress,
    taiko_maximum_combo = EXCLUDED.taiko_maximum_combo,
    taiko_play_count = EXCLUDED.taiko_play_count,
    taiko_play_time = EXCLUDED.taiko_play_time,
    taiko_pp = EXCLUDED.taiko_pp,
    taiko_ranked_score = EXCLUDED.taiko_ranked_score,
    taiko_replays_watched_by_others = EXCLUDED.taiko_replays_watched_by_others,
    taiko_total_hits = EXCLUDED.taiko_total_hits,
    taiko_total_score = EXCLUDED.taiko_total_score,
    fruits_count_100 = EXCLUDED.fruits_count_100,
    fruits_count_300 = EXCLUDED.fruits_count_300,
    fruits_count_50 = EXCLUDED.fruits_count_50,
    fruits_count_miss = EXCLUDED.fruits_count_miss,
    fruits_global_rank = EXCLUDED.fruits_global_rank,
    fruits_grade_counts_a = EXCLUDED.fruits_grade_counts_a,
    fruits_grade_counts_s = EXCLUDED.fruits_grade_counts_s,
    fruits_grade_counts_sh = EXCLUDED.fruits_grade_counts_sh,
    fruits_grade_counts_ss = EXCLUDED.fruits_grade_counts_ss,
    fruits_grade_counts_ssh = EXCLUDED.fruits_grade_counts_ssh,
    fruits_hit_accuracy = EXCLUDED.fruits_hit_accuracy,
    fruits_level_current = EXCLUDED.fruits_level_current,
    fruits_level_progress = EXCLUDED.fruits_level_progress,
    fruits_maximum_combo = EXCLUDED.fruits_maximum_combo,
    fruits_play_count = EXCLUDED.fruits_play_count,
    fruits_play_time = EXCLUDED.fruits_play_time,
    fruits_pp = EXCLUDED.fruits_pp,
    fruits_ranked_score = EXCLUDED.fruits_ranked_score,
    fruits_replays_watched_by_others = EXCLUDED.fruits_replays_watched_by_others,
    fruits_total_hits = EXCLUDED.fruits_total_hits,
    fruits_total_score = EXCLUDED.fruits_total_score,
    mania_count_100 = EXCLUDED.mania_count_100,
    mania_count_300 = EXCLUDED.mania_count_300,
    mania_count_50 = EXCLUDED.mania_count_50,
    mania_count_miss = EXCLUDED.mania_count_miss,
    mania_global_rank = EXCLUDED.mania_global_rank,
    mania_grade_counts_a = EXCLUDED.mania_grade_counts_a,
    mania_grade_counts_s = EXCLUDED.mania_grade_counts_s,
    mania_grade_counts_sh = EXCLUDED.mania_grade_counts_sh,
    mania_grade_counts_ss = EXCLUDED.mania_grade_counts_ss,
    mania_grade_counts_ssh = EXCLUDED.mania_grade_counts_ssh,
    mania_hit_accuracy = EXCLUDED.mania_hit_accuracy,
    mania_level_current = EXCLUDED.mania_level_current,
    mania_level_progress = EXCLUDED.mania_level_progress,
    mania_maximum_combo = EXCLUDED.mania_maximum_combo,
    mania_play_count = EXCLUDED.mania_play_count,
    mania_play_time = EXCLUDED.mania_play_time,
    mania_pp = EXCLUDED.mania_pp,
    mania_ranked_score = EXCLUDED.mania_ranked_score,
    mania_replays_watched_by_others = EXCLUDED.mania_replays_watched_by_others,
    mania_total_hits = EXCLUDED.mania_total_hits,
    mania_total_score = EXCLUDED.mania_total_score,
    team_flag_url = EXCLUDED.team_flag_url,
    team_id = EXCLUDED.team_id,
    team_name = EXCLUDED.team_name,
    team_short_name = EXCLUDED.team_short_name;
