insert
	into
	public.beatmaplive
(beatmap_id,
	user_id,
	beatmapset_id,
	"mode",
	status,
	stars,
	od,
	ar,
	bpm,
	cs,
	hp,
	length,
	drain_time,
	count_circles,
	count_sliders,
	count_spinners,
	max_combo,
	pass_count,
	play_count,
	fc_count,
	ss_count,
	favourite_count,
	ranked_date,
	submitted_date,
	last_updated,
	"version",
	title,
	artist,
	"source",
	tags,
	checksum)
select b.id,
	b.user_id,
	b.beatmapset_id,
	b.mode_int,
	b.status,
	b.difficulty_rating ,
	b.accuracy,
	b.ar,
	b.bpm,
	b.cs,
	b.drain,
	b.total_length,
	b.hit_length,
	b.count_circles,
	b.count_sliders,
	b.count_spinners,
	b.max_combo,
	b.passcount,
	b.playcount,
	0,
	0,
	b.beatmapset_favourite_count ,
	b.beatmapset_ranked_date,
	b.beatmapset_submitted_date,
	b.beatmapset_last_updated,
	b."version",
	b.beatmapset_title,
	b.beatmapset_artist,
	b.beatmapset_source,
	b.beatmapset_tags,
	b.checksum
from beatmap b
	left join beatmapLive bl on b.id = bl.beatmap_id
where beatmapset_ranked_date is not null and bl.beatmap_id is null;