DROP TABLE IF EXISTS beatmaps;

CREATE TABLE beatmaps (
    beatmapset_id INTEGER,
    difficulty_rating NUMERIC,
    id INTEGER PRIMARY KEY,
    mode TEXT,
    status TEXT,
    total_length INTEGER,
    user_id INTEGER,
    version TEXT,
    accuracy INTEGER,
    ar NUMERIC,
    bpm NUMERIC,
    convert BOOLEAN,
    count_circles INTEGER,
    count_sliders INTEGER,
    count_spinners INTEGER,
    cs NUMERIC,
    deleted_at TIMESTAMP WITH TIME ZONE,
    drain NUMERIC,
    hit_length INTEGER,
    is_scoreable BOOLEAN,
    last_updated TIMESTAMP WITH TIME ZONE,
    mode_int INTEGER,
    passcount INTEGER,
    playcount INTEGER,
    ranked INTEGER,
    url TEXT,
    checksum TEXT,
    max_combo INTEGER,
    beatmapset_artist TEXT,
    beatmapset_artist_unicode TEXT,
    beatmapset_creator TEXT,
    beatmapset_favourite_count INTEGER,
    beatmapset_hype JSONB,
    beatmapset_nsfw BOOLEAN,
    beatmapset_offset INTEGER,
    beatmapset_play_count INTEGER,
    beatmapset_preview_url TEXT,
    beatmapset_source TEXT,
    beatmapset_spotlight BOOLEAN,
    beatmapset_status TEXT,
    beatmapset_title TEXT,
    beatmapset_title_unicode TEXT,
    beatmapset_track_id INTEGER,
    beatmapset_user_id INTEGER,
    beatmapset_video BOOLEAN,
    beatmapset_bpm NUMERIC,
    beatmapset_can_be_hyped BOOLEAN,
    beatmapset_deleted_at TIMESTAMP WITH TIME ZONE,
    beatmapset_discussion_enabled BOOLEAN,
    beatmapset_discussion_locked BOOLEAN,
    beatmapset_is_scoreable BOOLEAN,
    beatmapset_last_updated TIMESTAMP WITH TIME ZONE,
    beatmapset_legacy_thread_url TEXT,
    beatmapset_ranked INTEGER,
    beatmapset_ranked_date TIMESTAMP WITH TIME ZONE,
    beatmapset_storyboard BOOLEAN,
    beatmapset_submitted_date TIMESTAMP WITH TIME ZONE,
    beatmapset_tags TEXT,
    failtimes JSONB,
    beatmapset_availability JSONB,
    owners JSONB,
    beatmapset_nominations_summary JSONB,
    beatmapset_covers JSONB,
    beatmapset_ratings JSONB
);