DROP TABLE IF EXISTS scoreStandard;

CREATE TABLE scoreStandard (
    id BIGINT PRIMARY KEY,
    beatmap_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    accuracy NUMERIC NOT NULL,
    best_id INTEGER NULL,
    build_id INTEGER NOT NULL,
    classic_total_score BIGINT NOT NULL,
    current_user_attributes JSONB NOT NULL,
    ended_at TIMESTAMPTZ NOT NULL,
    has_replay BOOLEAN NOT NULL,
    is_perfect_combo BOOLEAN NOT NULL,
    legacy_perfect BOOLEAN NOT NULL,
    legacy_score_id INTEGER NULL,
    legacy_total_score BIGINT NOT NULL,
    max_combo INTEGER NOT NULL,
    maximum_statistics_great INTEGER NOT NULL,
    maximum_statistics_ignore_hit INTEGER NOT NULL,
    maximum_statistics_slider_tail_hit INTEGER NOT NULL,
    mods JSONB NOT NULL,
    passed BOOLEAN NOT NULL,
    pp NUMERIC NOT NULL,
    preserve BOOLEAN NOT NULL,
    processed BOOLEAN NOT NULL,
    rank VARCHAR(3) NOT NULL,
    ranked BOOLEAN NOT NULL,
    replay BOOLEAN NOT NULL,
    ruleset_id INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    statistics_great INTEGER NOT NULL,
    statistics_ignore_hit INTEGER NOT NULL,
    statistics_slider_tail_hit INTEGER NOT NULL,
    total_score BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL
);
