DROP TABLE IF EXISTS scores;

CREATE TABLE scores (
    classic_total_score BIGINT,
    preserve BOOLEAN,
    processed BOOLEAN,
    ranked BOOLEAN,
    total_score_without_mods INTEGER,
    beatmap_id BIGINT,
    best_id BIGINT,
    id BIGINT PRIMARY KEY,
    rank VARCHAR(10),
    type VARCHAR(50),
    user_id BIGINT,
    accuracy NUMERIC,
    build_id BIGINT,
    ended_at TIMESTAMP WITH TIME ZONE,
    has_replay BOOLEAN,
    is_perfect_combo BOOLEAN,
    legacy_perfect BOOLEAN,
    legacy_score_id BIGINT,
    legacy_total_score BIGINT,
    max_combo INT,
    passed BOOLEAN,
    pp NUMERIC,
    ruleset_id INT,
    started_at TIMESTAMP WITH TIME ZONE,
    total_score BIGINT,
    replay BOOLEAN,
    user_avatar_url TEXT,
    user_country_code CHAR(2),
    user_default_group VARCHAR(50),
    user_is_active BOOLEAN,
    user_is_bot BOOLEAN,
    user_is_deleted BOOLEAN,
    user_is_online BOOLEAN,
    user_is_supporter BOOLEAN,
    user_last_visit TIMESTAMP WITH TIME ZONE,
    user_pm_friends_only BOOLEAN,
    user_profile_colour TEXT,
    user_username VARCHAR(255),
    user_team TEXT,
    statistics_great INT,
    statistics_ignore_hit INT,
    statistics_slider_tail_hit INT,
    maximum_statistics_great INT,
    maximum_statistics_ignore_hit INT,
    maximum_statistics_slider_tail_hit INT,
    mods JSONB,
    current_user_attributes JSONB,
    user_country JSONB,
    user_cover JSONB
);