CREATE TABLE scores (
    classic_total_score BIGINT,
    preserve BOOLEAN,
    processed BOOLEAN,
    ranked BOOLEAN,
    beatmap_id INTEGER,
    best_id BIGINT,
    id BIGINT PRIMARY KEY,
    rank TEXT,
    type TEXT,
    user_id INTEGER,
    accuracy NUMERIC,
    build_id INTEGER,
    ended_at TIMESTAMP WITH TIME ZONE,
    has_replay BOOLEAN,
    is_perfect_combo BOOLEAN,
    legacy_perfect BOOLEAN,
    legacy_score_id BIGINT,
    legacy_total_score BIGINT,
    max_combo INTEGER,
    passed BOOLEAN,
    pp NUMERIC,
    ruleset_id INTEGER,
    started_at TIMESTAMP WITH TIME ZONE,
    total_score BIGINT,
    replay BOOLEAN,
    statistics_great INTEGER,
    statistics_ignore_hit INTEGER,
    statistics_slider_tail_hit INTEGER,
    maximum_statistics_great INTEGER,
    maximum_statistics_ignore_hit INTEGER,
    maximum_statistics_slider_tail_hit INTEGER,
    mods JSONB,
    current_user_attributes JSONB
);