CREATE TABLE IF NOT EXISTS userOsu (
    id BIGINT PRIMARY KEY,
    avatar_url TEXT,
    cover_custom_url TEXT,
    cover_id BIGINT,
    cover_url TEXT,
    country_code VARCHAR(2),
    country_name TEXT,
    default_group TEXT,
    groups JSONB,
    is_active BOOLEAN,
    is_bot BOOLEAN,
    is_deleted BOOLEAN,
    is_online BOOLEAN,
    is_supporter BOOLEAN,
    last_visit TIMESTAMPTZ,
    osu_count_100 INTEGER,
    osu_count_300 INTEGER,
    osu_count_50 INTEGER,
    osu_count_miss INTEGER,
    osu_global_rank INTEGER,
    osu_global_rank_exp INTEGER,
    osu_grade_counts_a INTEGER,
    osu_grade_counts_s INTEGER,
    osu_grade_counts_sh INTEGER,
    osu_grade_counts_ss INTEGER,
    osu_grade_counts_ssh INTEGER,
    osu_hit_accuracy DOUBLE PRECISION,
    osu_is_ranked BOOLEAN,
    osu_level_current INTEGER,
    osu_level_progress INTEGER,
    osu_maximum_combo INTEGER,
    osu_play_count INTEGER,
    osu_play_time INTEGER,
    osu_pp DOUBLE PRECISION,
    osu_pp_exp DOUBLE PRECISION,
    osu_ranked_score BIGINT,
    osu_replays_watched_by_others INTEGER,
    osu_total_hits BIGINT,
    osu_total_score BIGINT,
    pm_friends_only BOOLEAN,
    profile_colour TEXT,
    team_flag_url TEXT,
    team_id INTEGER,
    team_name TEXT,
    team_short_name TEXT,
    username TEXT NOT NULL
);
