DROP TABLE IF EXISTS userExtended;

CREATE TABLE userExtended (
    "avatar_url" TEXT,
    "country_code" VARCHAR(10),
    "default_group" TEXT,
    "id" BIGINT PRIMARY KEY,
    "is_active" BOOLEAN,
    "is_bot" BOOLEAN,
    "is_deleted" BOOLEAN,
    "is_online" BOOLEAN,
    "is_supporter" BOOLEAN,
    "last_visit" TIMESTAMP WITH TIME ZONE,
    "pm_friends_only" BOOLEAN,
    "profile_colour" TEXT,
    "username" TEXT NOT NULL,
    "cover_url" TEXT,
    "discord" TEXT,
    "has_supported" BOOLEAN,
    "interests" TEXT,
    "join_date" TIMESTAMP WITH TIME ZONE,
    "location" TEXT,
    "max_blocks" INTEGER,
    "max_friends" INTEGER,
    "occupation" TEXT,
    "playmode" TEXT,
    "post_count" INTEGER,
    "profile_hue" INTEGER,
    "title" TEXT,
    "title_url" TEXT,
    "twitter" TEXT,
    "website" TEXT,
    "account_history" JSONB,
    "active_tournament_banner" TEXT,
    "active_tournament_banners" JSONB,
    "beatmap_playcounts_count" INTEGER,
    "comments_count" INTEGER,
    "favourite_beatmapset_count" INTEGER,
    "follower_count" INTEGER,
    "graveyard_beatmapset_count" INTEGER,
    "groups" JSONB,
    "guest_beatmapset_count" INTEGER,
    "loved_beatmapset_count" INTEGER,
    "mapping_follower_count" INTEGER,
    "nominated_beatmapset_count" INTEGER,
    "page" JSONB,
    "pending_beatmapset_count" INTEGER,
    "ranked_beatmapset_count" INTEGER,
    "scores_best_count" INTEGER,
    "scores_first_count" INTEGER,
    "scores_pinned_count" INTEGER,
    "scores_recent_count" INTEGER,
    "support_level" INTEGER,
    "team" TEXT,
    "rankHistory" JSONB,
    "ranked_and_approved_beatmapset_count" INTEGER,
    "unranked_beatmapset_count" INTEGER,
    "cover_custom_url" TEXT,
    "cover_id" TEXT,
    "statistics_count_100" INTEGER,
    "statistics_count_300" INTEGER,
    "statistics_count_50" INTEGER,
    "statistics_count_miss" INTEGER,
    "statistics_global_rank" INTEGER,
    "statistics_global_rank_exp" INTEGER,
    "statistics_pp" DECIMAL,
    "statistics_pp_exp" DECIMAL,
    "statistics_ranked_score" BIGINT,
    "statistics_hit_accuracy" DECIMAL,
    "statistics_play_count" INTEGER,
    "statistics_play_time" INTEGER,
    "statistics_total_score" BIGINT,
    "statistics_total_hits" BIGINT,
    "statistics_maximum_combo" INTEGER,
    "statistics_replays_watched_by_others" INTEGER,
    "statistics_is_ranked" BOOLEAN,
    "statistics_country_rank" INTEGER,
    "kudosu_available" INTEGER,
    "kudosu_total" INTEGER,
    "rank_highest_rank" INTEGER,
    "rank_highest_updated_at" TIMESTAMP WITH TIME ZONE,
    "daily_challenge_user_stats_daily_streak_best" INTEGER,
    "daily_challenge_user_stats_daily_streak_current" INTEGER,
    "daily_challenge_user_stats_last_update" TIMESTAMP WITH TIME ZONE,
    "daily_challenge_user_stats_last_weekly_streak" INTEGER,
    "daily_challenge_user_stats_playcount" INTEGER,
    "daily_challenge_user_stats_top_10p_placements" INTEGER,
    "daily_challenge_user_stats_top_50p_placements" INTEGER,
    "daily_challenge_user_stats_user_id" BIGINT,
    "daily_challenge_user_stats_weekly_streak_best" INTEGER,
    "daily_challenge_user_stats_weekly_streak_current" INTEGER,
    "country_name" TEXT,
    "replays_watched_counts" JSONB,
    "rank_history" JSONB,
    "statistics_level" JSONB,
    "badges" JSONB,
    "previous_usernames" JSONB,
    "profile_order" JSONB,
    "user_achievements" JSONB,
    "statistics_grade_counts" JSONB,
    "statistics_rank" JSONB,
    "monthly_playcounts" JSONB,
    "playstyle" JSONB
);
